import { binarySum } from "./addition-of-2-numbers";
import { bitwiseAndInRange } from "./bitwise-and-in-range";
import { copySetBitsInARange } from "./copy-set-bits-in-a-range";
import { countSetBitsInArray } from "./counting-set-bits-in-array";
import { divisionOf2Numbers } from "./division-of-2-numbers";
import { missingNumber } from "./missing-number";
import { multiplicationOf2Numbers } from "./multiplication-of-2-numbers";
import { numberOf1Bits } from "./number-of-1-bits";
import { stringPowerSet } from "./power-set";
import { reverseInteger } from "./reverse-a-number";
import { reverseBits } from "./reverse-bits";
import { setBitsInRange } from "./set-bits-in-a-range";
import { singleNumber } from "./single-number";
import { singleNumber3 } from "./single-number-3";
import { xorOfAllSubarrays } from "./xor-of-all-subarrays";

// console.log(singleNumber([2,3,4,4,3,1,1]));
// console.log(numberOf1Bits(11));
// console.log(countSetBitsInArray(5));
// console.log(reverseBits(8));
// console.log(missingNumber([3,0,1]));
// console.log(binarySum(2, 3));
// console.log(reverseInteger(1234));
// console.log(setBitsInRange(8, 1, 2));
// console.log(copySetBitsInARange(10, 13, 2,3));
// console.log(divisionOf2Numbers(-7, 3));
// console.log(multiplicationOf2Numbers(12,12));
// console.log(singleNumber3([1,2,1,3,2,5]));
// console.log(stringPowerSet('abc'));
// console.log(xorOfAllSubarrays([3, 5, 2, 4, 6]));
console.log(bitwiseAndInRange(6,7));
