import { findDuplicate } from "../arrays-and-hashing/find-duplicate";
import { binarySearch } from "./binary-search-intro";
import { findClosestElementInArray } from "./closest-element-in-array";
import { findPeakElement } from "./find-peak-element";
import { kokoBananas } from "./koko-bananas";
import { kthSmallestDistance } from "./kth-smallest-distance-pair";
import { medianOf2SortedArrays } from "./median-of-2-sorted-arrays";
import { minimumInRotated } from "./minimum-in-rotated-sorted-array";
import { minSessionsToCompleteWork } from "./number-of-sessions-to-complete-work";
import { pow } from "./power-function";
import { searchInRotatedArray } from "./search-in-rotated-sorted-array";
import { matrixSearch } from "./search-in-row-column-sorted-matrix";
import { splitArrayLargestSum } from "./split-array-largest-sum";
import { sqrt } from "./square-root";

// console.log(binarySearch([-1,0,3,5,9,12], 9));
// console.log(matrixSearch([[1,3,5,7],[10,11,16,20],[23,30,34,60]], 13));
// console.log(kokoBananas([3,6,7,11], 8));
// console.log(minimumInRotated([3,4,5,1,2]));
// console.log(searchInRotatedArray([4,5,6,7,0,1,2], 2));
// console.log(sqrt(25));
// console.log(findPeakElement([1,2,1,3,5,6,4]));
// console.log(pow(2, 9));
// console.log(kthSmallestDistance([1,3,1], 1));
// console.log(splitArrayLargestSum([1,2,3,4,5], 2));
// console.log(findDuplicate([1,3,2,4,2]));
// console.log(medianOf2SortedArrays([1,3], [2,4]));
// console.log(minSessionsToCompleteWork([1,2,3], 3));
console.log(findClosestElementInArray([0,0,1,2,3,3,4,7,7,8], 5));